spring:
  elasticsearch:
    uris: http://localhost:9200
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mtime?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: rootroot
  rabbitmq:
    port: 5672
    username: jarviz
    password: 123123
    virtual-host: jarvizhost